export const ADD_TO_CART = "ADD_TO_CART"; 
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const FILTERED_DATA = "FILTERED_DATA";
export const GET_PRODUCTLIST = "GET_PRODUCTLIST";